<a href="https://colab.research.google.com/github/marufjon1991mike-gif/data-science-practice/blob/main/8_26_NumPy_kutubxonasi_31_topshiriq.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

In [2]:
print(np.__version__)
print(np.show_config)

2.0.2
<function show at 0x7fea9f586fc0>


#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [3]:
arr = [0,1,2,3,4,5]
np.array(arr)

array([0, 1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---




In [4]:
arr_zeros = np.zeros(9)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [5]:
arr1 = np.arange(10)
np.size(arr1)
isize = arr1.itemsize
isize

8

#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [7]:
arr2 = np.zeros(12)
arr2[5] = 1
arr2

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [8]:
arr3 = np.arange(20,60)
arr3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [9]:
arr4 = np.arange(10)
arr4[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [10]:
arr5 = np.arange(12,21).reshape(3,3)
arr5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [11]:
arr6 = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(arr6)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [12]:
arr7 = np.random.random((2,2,2))
arr7

array([[[0.91761622, 0.18660654],
        [0.88251058, 0.45359039]],

       [[0.18535075, 0.93626899],
        [0.07337031, 0.6334505 ]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [13]:
arr8 = np.random.random((9,9))
arr8.min()
arr8.max()

np.float64(0.9994625692220581)

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [14]:
0 * np.nan

nan

In [15]:
np.nan == np.nan

False

In [16]:
np.inf > np.nan

False

In [17]:
np.nan - np.nan

nan

In [19]:
np.nan in set([np.nan])

True

In [18]:
0.7 == 7 * 0.1

False

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [20]:
arr9 = np.ones((6,3))
arr10 = np.ones((3,4))
np.dot(arr9,arr10)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [21]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [22]:
a = np.array([1,2])
b = np.array([4,5])
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [23]:
nparr = np.array(0)
print(nparr / nparr)
print(nparr // nparr)
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_22020/3202997016.py:2: RuntimeWarning: invalid value encountered in divide
  print(nparr / nparr)
/tmp/ipykernel_22020/3202997016.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(nparr // nparr)
/tmp/ipykernel_22020/3202997016.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [34]:
arra = np.arange(20)
arrb = np.arange(0,20,3)
arrans = np.intersect1d(arra,arrb)
arrans

array([ 0,  3,  6,  9, 12, 15, 18])

#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` % (Sonning kasr qismi - qoldiq), np.floor, astype, np.trunc

In [52]:
rand_arr = np.random.randn(10)
pos_rand_arr = rand_arr[rand_arr > 0]
print(np.floor(pos_rand_arr))
print(pos_rand_arr.astype(int))
print(np.trunc(pos_rand_arr))
print(pos_rand_arr - pos_rand_arr%1)


[1. 0. 0. 0. 1.]
[1 0 0 0 1]
[1. 0. 0. 0. 1.]
[1. 0. 0. 0. 1.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [87]:
arr = np.arange(9).reshape(3,3)
arr[:] = np.arange(3)
arr

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [86]:
arr = np.random.randn(10)
np.sort(arr)

array([-0.92739799, -0.43469028, -0.41736578, -0.36542864, -0.30092934,
       -0.02670818, -0.01921558,  0.46049112,  1.1057736 ,  2.62224932])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [65]:
A = np.random.rand(5)
B = np.random.rand(5)
print(np.array_equal(A,B))
print(np.allclose(A,B))

False
False


#### 23. 5 dan 15 gacha bo'lgan sonlardan iborat massiv yarating. Massivdagi 10 dan katta elementlarni ajratib oling va ularning yig‘indisini hisoblang.


`💡Ishora` sum()

In [85]:
arr = np.arange(5,15)
np.sum(arr[arr>10])

np.int64(50)

#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [84]:
arr = np.random.rand(5)
arr[np.argmax(arr)] = 0
arr

array([0.17809487, 0.17087638, 0.4413184 , 0.18229331, 0.        ])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [76]:
tdate = np.datetime64("today")
ydate = np.datetime64("today") - np.timedelta64(1,"D")
gdate = np.datetime64("today") + np.timedelta64(1,"D")
print(ydate)
print(tdate)
print(gdate)


2026-05-19
2026-05-20
2026-05-21


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [80]:
Jan_arr = np.arange("2016-01-01","2016-02-01",dtype="datetime64[D]")
Jan_arr

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 2.6, 7.9, 9.8, 4.2 elementlardan tashkil topgan arr yarating va uni arr1 deb nomlang. Keyin massivdagi har bir sonning butun qismini oling va yangi massiv - arr2 ni hosil qiling.


`💡Ishora` astype(int)

In [83]:
arr1 = [27., 2.6, 7.9, 9.8, 4.2]
arr2 = np.trunc(arr1)
arr2

array([27.,  2.,  7.,  9.,  4.])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [90]:
arr1 = np.arange(5)
arr2 = np.arange(5,10)
np.add.reduce(arr1+arr2)

np.int64(45)

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [100]:
arr = np.array([1, 2, 3, 4, 5])
result = np.zeros(len(arr)*4 - 3, dtype=int)
result[::4] = arr
print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [120]:
arr = np.random.randint(0,10,10)
arr = np.append(arr, [3, 9, 7, 5])
result = np.bincount(arr).argmax()
print(arr)
result

[2 7 0 5 7 2 9 9 5 5 3 9 7 5]


np.int64(5)

#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`